default_install_hook_types:
  - pre-commit
  - post-checkout
  - post-merge
  - post-rewrite
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-yaml
    args: [--unsafe]
  - id: check-toml
  - id: check-json
  - id: check-added-large-files
    args: [--maxkb=500]
  - id: check-merge-conflict
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.10.0
  hooks:
  - id: uv-lock
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.0
  hooks:
  - id: ruff-check
    args: [--fix]
    types_or: [python, pyi]
  - id: ruff-format
    types_or: [python, pyi]
- repo: local
  hooks:
  - id: ty
    name: ty check
    entry: uv run --frozen ty check
    language: system
    pass_filenames: false
    always_run: true
